/**
 * Queries - Read operations that don't modify state
 */

// Admin domain queries
export * from "./admin/GetAdminStats.query";
export * from "./admin/GetUserPaths.query";
export * from "./admin/GetUsers.query";
// Auth domain queries
export * from "./auth/GetUserAuthData.query";
export * from "./content/GetCategories.query";
export * from "./content/GetCategoryById.query";
export * from "./content/GetDomainById.query";
// Content domain queries
export * from "./content/GetDomains.query";
export * from "./content/GetFlashcardById.query";
export * from "./content/GetFlashcards.query";
export * from "./groups/GetAssignedPaths.query";
export * from "./groups/GetGroupAnalytics.query";
export * from "./groups/GetGroupDetail.query";
export * from "./groups/GetGroupLeaderboard.query";
// Groups domain queries
export * from "./groups/GetGroups.query";
export * from "./groups/GetInvitation.query";
export * from "./groups/GetMemberProgress.query";
export * from "./groups/GetMyGroups.query";
// Lesson domain queries
export * from "./lesson/GetLessonFlashcards.query";
export * from "./lesson/GetLessonInfo.query";
export * from "./lesson/GetLessonProgress.query";
export * from "./paths/GetLessonById.query";
export * from "./paths/GetLessons.query";
export * from "./paths/GetNextLesson.query";
export * from "./paths/GetNextLessonAfterCompletion.query";
export * from "./paths/GetPathById.query";
// Paths domain queries
export * from "./paths/GetPaths.query";
export * from "./paths/GetUnitById.query";
export * from "./paths/GetUnits.query";
export * from "./paths/IsLessonCompleted.query";
export * from "./paths/IsLessonUnlocked.query";
export * from "./paths/IsPathCompleted.query";
export * from "./paths/IsPathUnlocked.query";
export * from "./paths/IsUnitCompleted.query";
export * from "./paths/IsUnitUnlocked.query";
// Progress domain queries
export * from "./progress/GetConsecutiveDaysStreak.query";
export * from "./progress/GetUserProgress.query";
export * from "./review/GetCurrentStreak.query";
// Review domain queries
export * from "./review/GetDueCards.query";
export * from "./review/GetDueFlashcardsLegacy.query";
export * from "./review/GetFlashcardReviewHistory.query";
export * from "./review/GetLastReview.query";
export * from "./review/GetStrugglingCards.query";
export * from "./review/GetTodayReviewCount.query";
export * from "./review/IsCardStruggling.query";
export * from "./stats/GetLeaderboard.query";
// Stats domain queries
export * from "./stats/GetStats.query";
export * from "./stats/GetUserStats.query";
export * from "./stats/GetXPHistory.query";
export * from "./types";
