export type {
  AdminDashboardData,
  AdminStats,
  AdminUser,
  GetAdminStatsResult,
  GetUserPathsResult,
  GetUsersResult,
  PathWithAccess,
  RecentDomain,
  UserPathsResponse,
} from "./admin.dto";
export type { RegisterResult } from "./auth.dto";
export type {
  BulkCreateFlashcardsResult,
  CategoryExtended,
  CategoryFormInput,
  CategoryItem,
  CategoryListItem,
  CategoryWithDomain,
  CategoryWithFlashcardCount,
  CreateCategoryInput,
  CreateCategoryResult,
  CreateDomainInput,
  CreateDomainResult,
  CreateFlashcardInput,
  CreateFlashcardResult,
  DeleteResult,
  DomainExtended,
  DomainFormInput,
  DomainItem,
  DomainWithCreator,
  DomainWithGroup,
  DomainWithStats,
  FlashcardAdmin,
  FlashcardFormInput,
  FlashcardItem,
  FlashcardListItem,
  FlashcardWithCategory,
  FlashcardWithDomain,
  GetCategoriesResult,
  GetDomainsResult,
  GetFlashcardsResult,
  ReviewSession,
  StrugglingQueueWithFlashcard,
  UpdateCategoryInput,
  UpdateCategoryResult,
  UpdateDomainInput,
  UpdateDomainResult,
  UpdateFlashcardInput,
  UpdateFlashcardResult,
} from "./content.dto";
export type {
  CreateHeartsTransactionInput,
  CreateXPTransactionInput,
  DashboardStats,
  DomainProgress,
  GetStatsResult,
  GetUserProgressResult,
  HeartsTransactionWithDetails,
  RefillHeartsResult,
  StreakInfo,
  UpdateStreakResult,
  UserProgressExtended,
  UserProgressItem,
  UserProgressWithPath,
  XPTransactionWithDetails,
} from "./gamification.dto";

export type {
  CreateGroupInput,
  CreateGroupInvitationInput,
  CreateGroupMemberInput,
  CreateGroupPathInput,
  CreateGroupResult,
  GetAssignedPathsResult,
  GetGroupAnalyticsResult,
  GetGroupDetailResult,
  GetGroupLeaderboardResult,
  GetGroupsResult,
  GetInvitationResult,
  GetMemberProgressResult,
  GetMyGroupsResult,
  GroupAnalytics,
  GroupExtended,
  GroupFormInput,
  GroupInvitationExtended,
  GroupInvitationWithGroup,
  GroupLeaderboardEntry,
  GroupMemberExtended,
  GroupMemberWithUser,
  GroupPathWithDetails,
  GroupWithAdmin,
  GroupWithStats,
  MemberProgress,
  PathProgress,
  SendInvitationResult,
  SuccessResult,
  UpdateGroupInput,
  UpdateGroupInvitationInput,
} from "./groups.dto";
export type {
  CompleteLessonResult,
  CreateLessonCompletionInput,
  CreateLessonFlashcardInput,
  CreateLessonInput,
  CreatePathInput,
  CreateUnitInput,
  GetLessonFlashcardsResult,
  GetLessonInfoResult,
  GetLessonProgressResult,
  GetLessonsResult,
  GetPathsResult,
  GetUnitsResult,
  LessonAnswer,
  LessonCompletionWithDetails,
  LessonFormInput,
  LessonResult,
  LessonSession,
  LessonSessionFlashcard,
  LessonWithContext,
  LessonWithFlashcards,
  LessonWithProgress,
  PathFormInput,
  PathWithCreator,
  PathWithProgress,
  StartLessonResponse,
  SubmitAnswerResult,
  UnitFormInput,
  UnitWithPath,
  UnitWithProgress,
  UpdateLessonInput,
  UpdatePathInput,
  UpdateUnitInput,
} from "./learning-path.dto";

export type {
  DueCard,
  GetDueCardsResult,
  GetStrugglingCardsResult,
  RecordReviewResult,
  StartReviewSessionResult,
  StrugglingCard,
  SubmitReviewResult,
} from "./review.dto";

export type {
  GetLeaderboardResult,
  GetXPHistoryResult,
  GlobalLeaderboardEntry,
  LeaderboardData,
  XpHistoryData,
} from "./stats.dto";
